name: Repolinter Validation

on:
  push:
    paths:
      - '**/*.json'
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:

jobs:
  repolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Repolinter
        uses: newrelic/repolinter-action@v0.2.1
        with:
          rulesetFile: .github/config/repolinter-ruleset.json
